# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxtarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VPGZa5SJ5vhr/pnDtxNqo/ph/t9ux02KpVQPXod6X7cqXjmTDWL4BuJeIeTmXLgzUm6NzNX62NpAJt1lKIU/XJ/4YGufB/TnlK9SfPCJ/smmayqA4afaC2U0rrOgvNNB/WnYY8S4VqUt7atWHg/SgT+6wzNtTURVjbg2punmSQhZdkKpqtF8xkSslsRF+vNGHNzXhpTAYQHZsIDDN1RN5dgbz84MqboOpqStyMkv3amJVsLHzG5//5oEtQHHbAfVczrWDGUtZ8Qv2MjOWVRSmYIN70yCAhmTumpVvGbzcRQIsOalaUtXwidA2CZCdZatyNG/HAnSyT28DYzVBNM3HXCrS2JPahp7ICX4zcELVclA2cJdRyTHOXvrfgD2pCYhrZuNlS9/ujDije6+RJI7jO7/obS2+KFNX4V1C8wUs3GxyOwQINdMU54J7GHmnXHqzzMdqMoHgobM3aCp9B2g8nhjgnIf2vTKQZYaU0f/8BTtc2rVz/kGjQCtsYcbA9VT0lRBUVCtXqNKHT19fZ31xVFAURmxJ8FsjWqfXViVhSmYzdgfwM5xBKg98Qs9sfmXtUL5W7ql0eO5Yu/1KI0FYci846UNRdCk7Cch3VSAJjUtXwNppPQhO9tktx+Zg7ooD+uJM+kTiESuTaeWnGQNrpYZ56gCLuFsEX4p+g/UbVw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml