travis:
  secure:
    BINSTAR_TOKEN: ISMca3URPlgWvG9SjTDB+C/Y8QqTbuGhOlM2RTrj9xJ+1AaOHjIHhXfzYcRk/efaNECe3dsQCsQfnLzXGRiHPPVUCOIU6bM9fhMPPRsKHD9TlHOvjQIAYKOcKw5ohkIEe9PVmx5f5lFxhAgyQx/gF9/22E2ChuxpVwNCrKwO4b67maiaoya0R5YBU5ujRqS4lE+Q9zXix3xXkJmW4qigOF1Soi+EKTTjozT5QhbgFSpQ7izkCtesITagJQxwmA637wBcOxmDZ/6YHNOtFpUbhh/eGqPBh0yPn27Ltt0upf7QTu0P9dIqOTvykGin2oS1xpvrem+fxEhr8JkriW0hKvXG9DzF7rTe3/aVSN4G2qmuVswxDN9uDhgf9UAhyNGTCR9KcLCo8ldGoIhe88VISE+U/rWA9ho7kQsw9ClpzB0VUy2ICYuLJegctFYkgumakmM/vd3pbqitZY8v5LfywkVfVQuApgSFbSPAnhini4an87yC7spSw0U0aCAyvsTCSEAQzH6TrxSGAN09dU0XCPZrF+LtBWvXUIGDofoYO9dFphNLAxM64LJ2BdNR9ZxSv2HPh5PFvhwwIWtCMJnhr3jVLAmGSIDKDzBkadrbYX/d6iV/qwx4n3bjLHCsF7ppp7reOhNKn+L/yHW+pwShmfOVnH2cNcaGL7v2sSFSI0s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
